stages:
  - lint
  - build
  - test
  - push
  - docs
  - trigger
  - cleanup

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

# Not making these global variables because they would get overridden in multi-project pipelines
.variables: &variables
  # The base of this repo's docker registry
  REPO_DOCKER_REGISTRY: ${CI_REGISTRY_IMAGE}
  # The image name of binaryninja-haskell image
  BLAZE_BINARYNINJA_HASKELL_IMAGE:
    ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/binaryninja-haskell/binaryninja-haskell
  # Enable buildkit for more efficient layer caching
  DOCKER_BUILDKIT: "1"

# Potential build dependencies for the dind host
.script-bootstrap-dind: &script-bootstrap-dind
  - echo -e "section_start:`date +%s`:bootstrap[collapsed=true]\r\e[0KBootstrap build dependencies"
  - |
    if [ -f /etc/alpine-release ]; then
      apk add git coreutils python3
      apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/testing time
    fi
  - echo -e "section_end:`date +%s`:bootstrap\r\e[0K"

# Print runner environment info for debugging
.script-before-info: &script-before-info
  - echo -e "section_start:`date +%s`:pre-env[collapsed=true]\r\e[0KEnvironment info (before_script)"
  - uname -a
  - env
  - ls -al
  - find . -maxdepth 1 \( ! -name . \) -print0 | sort -z | xargs -0 -x du -bhsc
  - df -h
  - date -Iseconds
  - |
    if type git >/dev/null; then
      pushd "$BLAZE_BINJA_API" >/dev/null && \
        { git log --color --decorate HEAD^..HEAD | cat || true;
          popd >/dev/null;
        } || true
    fi
  - |
    if type python3 >/dev/null; then
      python3 -c 'import binaryninja; print(binaryninja.core_version())' || true
    fi
  - echo -e "section_end:`date +%s`:pre-env\r\e[0K"

.dind:
  image: docker:dind
  tags:
    - dind
  timeout: 1h
  variables:
    <<: *variables
  before_script:
    - *script-bootstrap-dind
    - *script-before-info

.haskell-job:
  extends: .dind
  image: ${REPO_DOCKER_REGISTRY}/blaze:commit-${CI_COMMIT_SHA}
  # Skip .dind before_script, especially the environment info, since we don't
  # care about most of it after the build stage
  before_script:
    - *script-before-info

lint:
  stage: lint
  extends: .dind
  image: ${BLAZE_BINARYNINJA_HASKELL_IMAGE}
  needs: []
  script:
    - hlint --color=always src test demo
  allow_failure: true

# We need 2 build jobs: one for branch pipelines and one for MR pipelines
# - build:branch pushes to
#   - ${image}:commit-${CI_COMMIT_SHA}
#   - ${image}:branch-${CI_COMMIT_REF_SLUG}
#   For instance, ${project}:branch-feature-foo and ${project}:commit-1a2b3c4...
# - build:detached pushes to
#   - ${image}:merge-${CI_MERGE_REQUEST_IID}
#   For instance, ${project}:merge-71
# In either case, we should first try pulling the latest image for this branch or MR,
# and if that fails, pull :latest. This ensures we have cached layers downloaded

build:branch:
  stage: build
  extends: .dind
  rules:
    - if: $CI_MERGE_REQUEST_IID == null
  needs: []
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze

    - echo -e "section_start:`date +%s`:docker-pull[collapsed=true]\r\e[0KPull docker images for caching"
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker pull "${image}:branch-${CI_COMMIT_REF_SLUG}" ||
      docker pull "${image}:latest" ||
      true
    - echo -e "section_end:`date +%s`:docker-pull\r\e[0K"

    - echo -e "section_start:`date +%s`:docker-build\r\e[0KBuild docker image"
    - \time -v docker build --pull . -f Dockerfile
      --build-arg "CI_REGISTRY=${CI_REGISTRY}"
      --build-arg "CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}"
      -t "${image}:commit-${CI_COMMIT_SHA}"
      -t "${image}:branch-${CI_COMMIT_REF_SLUG}"
    - echo -e "section_end:`date +%s`:docker-build\r\e[0K"

    - echo -e "section_start:`date +%s`:docker-push[collapsed=true]\r\e[0KPush new docker image"
    - docker push "${image}:commit-${CI_COMMIT_SHA}"
    - docker push "${image}:branch-${CI_COMMIT_REF_SLUG}"
    - echo -e "section_end:`date +%s`:docker-push\r\e[0K"

build:detached:
  stage: build
  extends: .dind
  rules:
    - if: $CI_MERGE_REQUEST_IID
  needs: []
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze

    - echo -e "section_start:`date +%s`:docker-pull[collapsed=true]\r\e[0KPull docker images for caching"
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker pull "${image}:merge-${CI_MERGE_REQUEST_IID}" ||
      docker pull "${image}:latest" ||
      true
    - echo -e "section_end:`date +%s`:docker-pull\r\e[0K"

    - echo -e "section_start:`date +%s`:docker-build\r\e[0KBuild docker image"
    - \time -v docker build --pull . -f Dockerfile
      --build-arg "CI_REGISTRY=${CI_REGISTRY}"
      --build-arg "CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}"
      -t "${image}:merge-${CI_MERGE_REQUEST_IID}"
    - echo -e "section_end:`date +%s`:docker-build\r\e[0K"

    - echo -e "section_start:`date +%s`:docker-push[collapsed=true]\r\e[0KPush new docker image"
    - docker push "${image}:merge-${CI_MERGE_REQUEST_IID}"
    - echo -e "section_end:`date +%s`:docker-push\r\e[0K"

# Likewise, we need 2 test jobs. The test:branch job uses the ${image}:commit-... image,
# and the test:detached uses the ${image}:merge-... image

test:branch:
  stage: test
  extends: .haskell-job
  rules:
    - if: $CI_MERGE_REQUEST_IID == null
  needs:
    - build:branch
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cd /blaze/build/blaze
    - STACK_TEST_TIMEOUT=1800 .ci/scripts/run_stack_test.py

test:detached:
  stage: test
  extends: .haskell-job
  image: ${REPO_DOCKER_REGISTRY}/blaze:merge-${CI_MERGE_REQUEST_IID}
  rules:
    - if: $CI_MERGE_REQUEST_IID
  needs:
    - build:detached
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cd /blaze/build/blaze
    - STACK_TEST_TIMEOUT=1800 .ci/scripts/run_stack_test.py

# If we just pushed to the default branch, tag the image as :latest and push

push:latest:
  stage: push
  extends: .dind
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - test:branch
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker pull "${image}:commit-${CI_COMMIT_SHA}"
    - docker tag "${image}:commit-${CI_COMMIT_SHA}" "${image}:latest"
    - docker push "${image}:latest"

pages:
  extends: .haskell-job
  stage: docs
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_ID == null
      when: on_success
    - if: $CI_MERGE_REQUEST_ID == null
      when: manual
  needs:
    - test:branch
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - haddock_flags=(--no-haddock-deps)
    - pushd /blaze/build/blaze
    - stack haddock "${haddock_flags[@]}"
    - docs_dir=$(stack path --snapshot-doc-root "${haddock_flags[@]}")
    - popd
    # - cp -arT "$docs_dir" public
    - mkdir public
    - touch public/index.html
  allow_failure: true
  artifacts:
    paths:
      - public
    expire_in: 12 hours

trigger-blaze-ui:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: trigger
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine
  script:
    - apk add curl
    - curl --fail-with-body
        -X POST
        -F token=\"${CI_JOB_TOKEN}\"
        -F ref=master
        \"${CI_API_V4_URL}\"/projects/\"${BLAZE_UI_REPO_ID}\"/trigger/pipeline

cleanup:
  stage: cleanup
  when: always
  extends: .dind
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache --update bash
    - "# Untag all images created by this pipeline so we don't waste space on CI runner"
    - |
      bash -c '
        images=(${REPO_DOCKER_REGISTRY}/blaze)
        tags=()
        for image in "${images[@]}"; do
          tags+=(
            "${image}:commit-${CI_COMMIT_SHA}"
            "${image}:branch-${CI_COMMIT_REF_SLUG}"
            "${CI_MERGE_REQUEST_IID:+${image}:merge-${CI_MERGE_REQUEST_IID}}"
            "${CI_COMMIT_TAG:+${image}:tag-${CI_COMMIT_TAG}}"
            )
        done
        for i in "${!tags[@]}"; do if [ -z "${tags[$i]}" ]; then unset tags[$i]; fi; done
        echo "${tags[@]}"
        docker image rm "${tags[@]}" || true
      '
