.haskell-job: &haskell-job
  image: "haskell:8.8"
  tags:
    - dind
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack

before_script:
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - |
    for project in binary-analysis haskell-binja binja-header-cleaner; do
      [ -d "../$project" ] && git -C "../$project" pull || {
        rm -rf "../$project";
        git clone ${CI_REPOSITORY_URL%/*}/"$project" "../$project";
      }
    done

cache: &global-cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .stack/
    - .stack-work/

build:
  <<: *haskell-job
  stage: build
  #needs: []  # gitlab 12.8
  script: |
    stack build
  artifacts:
    paths:
      - .stack-work/

docs:
  <<: *haskell-job
  stage: test
  needs:
    - build
  script: |
    stack haddock
  artifacts:
    paths:
      - .stack/
      - .stack-work/

pages:
  <<: *haskell-job
  stage: deploy
  needs:
    - docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "haddock" || $CI_PIPELINE_SOURCE == "trigger"'
  script: |
    cp -arT "`stack path --snapshot-doc-root`" public
  artifacts:
    paths:
      - public
