stages:
  - deps
  - build
  - test
  - docs
  - deploy

.haskell-job: &haskell-job
  #image: ${CI_REGISTRY}/blaze/blaze/blaze-deps:${CI_COMMIT_REF_SLUG}
  image: ${CI_REGISTRY}/blaze/blaze-system/haskell-binaryninja-base:ci
  tags:
    - dind
  variables: &haskell-job-variables
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
    CACHE_FALLBACK_KEY: ${CI_DEFAULT_BRANCH}
  cache: &haskell-job-cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack/
      - .stack-work/

before_script:
  - env
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - |
    for project in binary-analysis haskell-binja binja-header-cleaner; do
      rm -rf "../$project"
      git clone --depth=1 ${CI_REPOSITORY_URL%/*}/"$project" "../$project"
    done

build:
  <<: *haskell-job
  stage: build
  #needs: ["deps"]
  script:
    - stack build

test:
  <<: *haskell-job
  stage: test
  needs: ["build"]
  script:
    - stack test

pages:
  <<: *haskell-job
  stage: deploy
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: manual
  script:
    - stack haddock
    - cp -arT "$(stack path --snapshot-doc-root)" public
  artifacts:
    paths:
      - public
