name:                blaze
version:             0.1.0.0
github:              "haskell-blaze"
license:             BSD3
author:              ""
maintainer:          ""
copyright:           "2019 Kudu Dynamics"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the readme

dependencies:
  - attoparsec
  - algebraic-graphs
  - base >= 4.7 && < 5
  - bimap
  - casing
  - containers
  - data-binary-ieee754
  - envy
  - binja
  - lens
  - mtl
  - newtype
  - pretty-simple
  - protolude
  - random
  - raw-strings-qq
  - recursion-schemes
  - sbv >= 8.0
  - stm
  - template-haskell
  - text
  - transformers
  - uuid
  - vector

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude   
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
#  - StrictData
  - TupleSections
  - TypeFamilies

  
library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j
  - +RTS
  - -s
  - -A256m
  - -n16m
  - -RTS
  source-dirs: src
  exposed-modules:
  - Blaze.Graph.Alga
  - Blaze.Prelude
  - Blaze.Path
  - Blaze.Pil
  - Blaze.Pil.Path
  - Blaze.Types.Pil
  
  
include-dirs:
  - "src"

tests:
  haze-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - blaze
    - binja
    - hspec
    - text
