name:                blaze
version:             0.1.0.0
github:              "haskell-blaze"
license:             BSD3
author:              ""
maintainer:          ""
copyright:           "2019 Kudu Dynamics"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the readme

dependencies:
  - algebraic-graphs
  - async
  - attoparsec
  - base >= 4.7 && < 5
  - bimap
  - binja
  - bv
#  - bv-sized
  - casing
  - containers
  - data-binary-ieee754
  - envy
#  - ghc-typelits-natnormalise
  - lens
  - list-t
  - mtl
  - newtype
  - parameterized-utils
  - pretty-simple
  - protolude
  - random
  - raw-strings-qq
  - recursion-schemes
  - sbv >= 8.6
  - stm
  - streamly
  - string-conversions
  - template-haskell
  - text
  - transformers
  - unordered-containers
  - uuid
  - vector


default-extensions:
  - BangPatterns
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
#  - StrictData
  - TupleSections
  - TypeFamilies


library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j
  - -O2
  source-dirs:
  - src
  exposed-modules:
  - Blaze.Cfg
  - Blaze.Fir
  - Blaze.Graph
  - Blaze.Graph.Alga
  - Blaze.Prelude
  - Blaze.Path
  - Blaze.Pil
  - Blaze.Pil.Analysis
  - Blaze.Pil.Construct
  - Blaze.Pil.Display
  - Blaze.Pil.Inference
  - Blaze.Pil.Path
  - Blaze.Pretty
  - Blaze.Solver
  - Blaze.Types.Fir
  - Blaze.Types.Pil
  - Blaze.Types.Pil.Analysis
  - Blaze.Types.Graph
  - Blaze.Types.Solver
  - Blaze.Search
  - Blaze.Function
  - Blaze.Types.Function
#  - Blaze.Liquid.Checker
  # scratch
  # - Blaze.PathScratch

include-dirs:
  - "src"
  - "../haskell-binja/res"

executables:
  blaze-profile:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blaze
    - containers
    - binja
    - hspec
    - text

  demo:
    main: Main.hs
    source-dirs:  demo
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blaze
    - containers
    - binja
    - hspec
    - text

benchmarks:
  call-graph-benchmark:
    main:                CallGraph.hs
    source-dirs:         benchmarks
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blaze
    - binja
    - text
    #- criterion

tests:
  blaze-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-graphs
    - containers
    - blaze
    - binja
    - hspec
    - text
